[package]
name = "dyrah_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.27.0", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
